name: Spring Boot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: guarderiasql
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cargar base de datos
        run: |
          PGPASSWORD=postgres psql \
            -h localhost \
            -U postgres \
            -d guarderiasql \
            -f database.sql

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Ejecutar tests y compilar
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/guarderiasql
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: ./mvnw clean verify